{{- if .Values.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $imageTag := .Values.image.tag -}}
{{- $imageEnv := .Values.image.env -}}
{{- $imageBranch := .Values.image.branch -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s" .Release.Name | trunc 63 }}
  labels:
    app: {{ printf "%s" .Release.Name | trunc 63 }}
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    env: {{ .Values.image.env }}
{{- if .Values.ingress.annotations }}
  annotations:
    {{ toYaml .Values.ingress.annotations | indent 4 | trim }}
{{- end }}
spec:
  rules:
  {{- range $host := .Values.ingress.hosts }}
    - http:
        paths:
        {{- range $item := $.Values.ingress.paths.proxy_pass }}
        - backend:
            service:
              name: {{ printf "%s" $releaseName | trunc 63 }}-{{ .serviceName }}-proxy-pass
              port:
                number: {{ .servicePort }}
          path: {{ .path }}
          pathType: Prefix
        {{- end -}}
        {{- range $item := $.Values.ingress.paths.default }}
        - backend:
            service:
              name: {{ printf "%s" $releaseName | trunc 63 }}
              port:
                number: {{ int .servicePort }}
          path: {{ .path }}
          pathType: Prefix
        {{- end -}}
    {{- if not (empty $host) }}
      host: {{ tpl $host $ }}
    {{- end }}
  {{- end -}}
{{- end }}
