apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  annotations:
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/target-type: ip
          alb.ingress.kubernetes.io/subnets: subnet-ede9aacc,subnet-eab987e4,subnet-4ce7a32a
          alb.ingress.kubernetes.io/tags: Environment=Production,Team=Archdaily
          alb.ingress.kubernetes.io/success-codes: '200'
          alb.ingress.kubernetes.io/healthcheck-path: /projects?continent_name=asia&fetch_at=2020&site=cl
          alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
          alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort:  {{ .Values.ingress.servicePort }}
