apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}
spec:
  limits:
  - default:
      memory: {{ .Values.limits.default_memory }}
    defaultRequest:
      memory:  {{ .Values.limits.drequest_memory }}
    type: Container
